### PR TITLE
updated data in about us, sig, r|p

### PR DESCRIPTION
**Pull request by faddock**
Updated data with information from google doc
Commented out SIGs with no information in document

### CODE REVIEW

**Comment by m-pitera** [comment]
image
Would you also be able to change the "Top4" Header to say "Officers" instead

With that We'd be able to merge it in and mark the issue as done 👍

**Comment by faddock** [comment]
@m-pitera made the change. Thanks for letting me contribute to the website.

**Comment by m-pitera** [comment]
Of course! Thanks for contributing!

**Comment by m-pitera** [comment]
i had to revert these changes because on the about page it only displayed the chair and not the rest
image

**Pull request merged**
